name: xave
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.13
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  eva_icons_flutter: ^3.1.0
  firebase_auth: ^3.3.16
  firebase_core: ^1.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  google_sign_in: ^5.3.0
  hive_flutter: ^1.1.0
  json_annotation: ^4.5.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  json_serializable: ^6.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
